### ISSUE TITLE
Crash after Install

### ISSUE THREAD

**Issue by HaloRings** [GeorgeDewar/worshiphelper-plugin#13] opened 2022-07-04 16:39 UTC
Hello, just discover this plugin and want to try it out.

Right after I install the plugin. PowerPoint crash.

Using Window 10 and PowerPoint 2016

https://user-images.githubusercontent.com/35905328/177193238-15694af3-601d-4f16-9d58-76b577c71660.mp4

**Comment by GeorgeDewar** [comment] 2022-07-04 19:37
Hi @HaloRings, thanks for this report and for including the great video and details.

I'll have a look into it and see what I can do.

**Comment by GeorgeDewar** [comment] 2022-07-12 10:31
Hi @HaloRings, I have installed Office 2016 in a virtual machine on Windows 10 but strangely still cannot reproduce the problem. It's not just you, though, I have seen the same on another PC which I don't have such easy access to.

Could you find the exact version (including whether it's 32-bit or 64-bit) for me by going File -> Account -> About Powerpoint?

![image](https://user-images.githubusercontent.com/5344417/178469795-4f56cfff-8f88-42cd-b312-fd88d4d969a8.png)

You should see a screen that looks like this:

![image](https://user-images.githubusercontent.com/5344417/178469529-2555cdca-0dbf-4277-843c-b5d952f425dc.png)

If you can send me those screenshots, or just the version number (1802 in my first image) and the orange text like in my second image, I may have a better shot at reproducing it.

If you can, please also go to "About your PC" from the Start menu and let me know the OS Version and Build numbers - for example, in my test VM:

![image](https://user-images.githubusercontent.com/5344417/178470551-85cb9b71-f6f5-469a-aca3-9bcc9d9d24c4.png)

One more question - do you have any other 3rd-party plugins installed as well?

**Comment by HaloRings** [comment] 2022-08-21 23:07
Hello @GeorgeDewar, sorry for the late reply.


Here are the screenshots:
![Screenshot_36](https://user-images.githubusercontent.com/35905328/185814172-6b7fb5e4-5ba5-49ac-86f7-3331c2bc5166.png)

![Screenshot_37](https://user-images.githubusercontent.com/35905328/185814179-82355868-0adf-460f-a521-b9e169028950.png)

![Screenshot_38](https://user-images.githubusercontent.com/35905328/185814192-cb6582f3-d40d-4dde-927c-503f50e5aa36.png)

and 3rd-party plugins installed, not that I know of.

**Comment by GeorgeDewar** [comment] 2022-08-23 07:55
Hi @HaloRings, thanks so much for sharing this. I see that you have the 64-bit version of Office, and after installing that myself I'm now able to reproduce the issue. It would appear that the issue it only affects 64-bit versions of Office.

Since I can reproduce it at last, I will almost certainly be able to fix it, so watch this space.

**Comment by HaloRings** [comment] 2022-08-25 01:57
Hi @GeorgeDewar , Yes it work! thank you so much!

https://user-images.githubusercontent.com/35905328/186554768-6060954b-e55a-46b0-8bbc-8de79f563ba3.mp4

Just a few question,

- How do I change the background from the default?

- Where to find and add the translations of KJV, NIV...ect

**Comment by GeorgeDewar** [comment] 2022-08-25 11:02
That's great news @HaloRings! Now to answer your questions:

### Backgrounds

Regarding the backgrounds, it's currently an "undocumented feature". I do intent to make it easier, but for now what you have to do is find the current default template which should be located in `C:\Program Files (x86)\WorshipHelper\Data\Templates` (if you installed WorshipHelper in the default location) and is named Default.pptx.

Copy that file to your user scripture templates directory, which is located at `%USERPROFILE%\Documents\WorshipHelper\UserTemplates\Scripture`, or in other words find the WorshipHelper directory in your documents folder (this gets created on first launch of the Insert Scripture dialog) and then browse to UserTemplates and then to Scripture.

Then rename it to the name of your choice, open it up and edit it as required, in your case changing the background, but you could also change the text colour or font, for example. You must not delete either of the existing text boxes, or WorshipHelper won't know where to put the content.

Your new template will then be selectable from the Insert Scripture dialog, and your choice will be remembered so you don't have to choose it each time.

Alternatively you can modify Default.pptx directly, but it requires admin privileges each time you do, and it's useful to have a backup in case you break it.

### Extra translations

The bible translations are located in C:\Program Files (x86)\WorshipHelper\Data\Bibles, and any new ones you put in there should work. They are in the format used by OpenSong. Luckily, both of the translations you mention are available on [OpenSong's website](http://www.opensong.org/home/download) to download. They are ZIP files, so extract the XMM file from inside. In the case of NIV, the file inside the ZIP seems to be lacking its xmm extension so you'd need to rename it to put ".xmm" on the end. Then drop both xmm files into that Bibles folder and you should be done.

**Comment by GeorgeDewar** [comment] 2022-08-25 11:03
Now that this particular issue is solved I will close it, but feel free to keep commenting, or email me if you have further questions - george@dewar.co.nz.

**Closed by GeorgeDewar** 2022-08-25 11:03 UTC
